{{ define "gluon.wait.wait-job.base" -}}
{{- if .Values.waitJob }}
{{- if .Values.waitJob.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Name }}-wait-job"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10000"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
spec:
  template:
    metadata:
      labels:
        wait-job: enabled
    spec: 
      serviceAccountName: "{{ .Release.Name }}-wait-job-sa"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000 
      restartPolicy: Never
      imagePullSecrets:
        - name: private-registry
      initContainers:
        - name: network-wait-online
          image: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.33.5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/bash"
          - "-c"
          - |
            attempts=0
            until kubectl auth can-i --list --namespace $K8S_NAMESPACE > /dev/null; do
              attempts=$((attempts+1))
              if [ $attempts -ge 10 ]; then
                echo "Network is unreachable after 10 attempts, exiting."
                exit 1
              fi
              echo "Network is unreachable, retrying in 6 seconds..."
              sleep 6
            done
          env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      containers:
      - name: wait-job
        image: "registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.33.5"
        imagePullPolicy: IfNotPresent
        workingDir: /wait
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - "/bin/bash"
        - "-c"
        - |
          if [[ -d /src && -n "$(ls /src/* 2>/dev/null)" ]]; then
            cp /src/* /wait/
          fi
          if [[ -n "$(ls . 2>/dev/null)" ]]; then
            for script in *; do
              if [[ -d ${script} ]]; then
                continue;
              fi
              chmod +x ${script}
              echo "---"
              echo "Running ${script}..."
              echo "---"
              ./${script}
            done
          fi
        resources:
          limits:
            cpu: 0.5
            memory: 128Mi
          requests:
            cpu: 0.5
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: workdir
            mountPath: /wait   
          - name: wait-scripts
            mountPath: /src
      volumes:
        - name: workdir
          emptyDir: {}  
        - name: wait-scripts
          configMap:
            name: "{{ .Release.Name }}-wait-script"
{{- end }}
{{- end }}
{{- end }}
---
{{ define "gluon.wait.wait-job-sa.base" -}}
{{- if .Values.waitJob }}
{{- if .Values.waitJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-wait-job-sa"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation, hook-failed
automountServiceAccountToken: true
{{- end }}
{{- end }}
{{- end }}
---
{{ define "gluon.wait.wait-job-role.base" -}}
{{- if .Values.waitJob }}
{{- if .Values.waitJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-wait-job-role"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation, hook-failed
rules:
- apiGroups:
  {{- with .Values.waitJob.permissions.apiGroups | default (list "") }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
  {{- with .Values.waitJob.permissions.resources | default (list "pods" ) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  verbs: 
  {{- with .Values.waitJob.permissions.verbs | default (list "get"  "list"  "watch") }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{ define "gluon.wait.wait-job-rolebinding.base" -}}
{{- if .Values.waitJob }}
{{- if .Values.waitJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-wait-job-rolebinding"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation, hook-failed
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-wait-job-sa"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-wait-job-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
---
{{- define "gluon.wait.wait-job.overrides" -}}
{{- $values := (first .) }}
{{- if $values.Values.waitJob }}
{{- if $values.Values.waitJob.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-{{ $values.Release.Name }}-wait-job-to-anywhere-any-port
  namespace: {{ $values.Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
  podSelector:
    matchLabels:
      wait-job: enabled
  policyTypes:
    - Egress
---
{{ include "gluon.util.merge" (append . "gluon.wait.wait-job.base") | nindent 0 -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- define "gluon.wait.wait-job-sa.overrides" -}}
{{- $values := (first .) }}
{{- if $values.Values.waitJob }}
{{- if $values.Values.waitJob.enabled }}
{{- include "gluon.util.merge" (append . "gluon.wait.wait-job-sa.base") | nindent 0 -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- define "gluon.wait.wait-job-role.overrides" -}}
{{- $values := (first .) }}
{{- if $values.Values.waitJob }}
{{- if $values.Values.waitJob.enabled }}
{{- include "gluon.util.merge" (append . "gluon.wait.wait-job-role.base") | nindent 0 -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- define "gluon.wait.wait-job-rolebinding.overrides" -}}
{{- $values := (first .) }}
{{- if $values.Values.waitJob }}
{{- if $values.Values.waitJob.enabled }}
{{- include "gluon.util.merge" (append . "gluon.wait.wait-job-rolebinding.base") | nindent 0 -}}
{{- end -}}
{{- end -}}
{{- end -}}
