{{- define "gluon.wait.wait-job-configmap.base" }}
{{- if .Values.waitJob }}
{{- if .Values.waitJob.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-wait-script"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    sidecar.istio.io/inject: "false"
  labels:
    wait-job: enabled
  namespace: {{ .Release.Namespace }}
data:
  {{ (.Files.Glob "wait/*").AsConfig | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}

{{- define "gluon.wait.wait-job-configmap.overrides" }}
{{- $values := (first .) }}
{{- if $values.Values.waitJob }}
{{- if $values.Values.waitJob.enabled }}
{{- include "gluon.util.merge" (append . "gluon.wait.wait-job-configmap.base") | nindent 0 }}
{{- end }}
{{- end }}
{{- end }}
