{{- define "gluon.tests.cypress-netpol.tpl" }}
{{- if ne false ((.Values.bbtests).cypress).enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-{{ .Release.Name }}-cypress-test-to-anywhere-any-port
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
  podSelector:
    matchLabels:
      helm-test: enabled
  policyTypes:
    - Egress
{{- end }}
{{- end }}
