{{- define "gluon.tests.script-sa" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-script-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-5"
{{- end }}

{{- define "gluon.tests.script-role" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-script-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups:
  {{- if and .Values.bbtests .Values.bbtests.scripts .Values.bbtests.scripts.permissions .Values.bbtests.scripts.permissions.apiGroups }}
    {{- toYaml .Values.bbtests.scripts.permissions.apiGroups | nindent 4 }}
  {{- else }}
    - ""
  {{- end }}
  resources:
  {{- if and .Values.bbtests .Values.bbtests.scripts .Values.bbtests.scripts.permissions .Values.bbtests.scripts.permissions.resources }}
    {{- toYaml .Values.bbtests.scripts.permissions.resources | nindent 4 }}
  {{- else }}
    - configmaps
  {{- end }}
  verbs:
  {{- if and .Values.bbtests .Values.bbtests.scripts .Values.bbtests.scripts.permissions .Values.bbtests.scripts.permissions.verbs }}
    {{- toYaml .Values.bbtests.scripts.permissions.verbs | nindent 4 }}
  {{- else }}
    - get
    - list
    - create
    - delete
  {{- end }}
{{- end }}

{{- define "gluon.tests.script-rolebinding" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-script-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-script-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-script-sa
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- define "gluon.tests.script-rbac" }}
{{- include "gluon.tests.script-sa" . }}
---
{{- include "gluon.tests.script-role" . }}
---
{{- include "gluon.tests.script-rolebinding" . }}
{{- end }}
