{{- define "gluon.tests.script-runner.tpl" -}}
{{- if ne false ((.Values.bbtests).scripts).enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-{{ .Chart.Name }}-script-test-to-anywhere-any-port
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
  podSelector:
    matchLabels:
      helm-test: enabled
  policyTypes:
    - Egress
---
kind: Pod
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-script-test"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "10"
  labels:
    helm-test: enabled
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  {{- if hasKey .Values "istio" }}
  {{- if and .Values.bbtests .Values.istio.enabled }}
  {{- $ingressGateway := (lookup "v1" "Service" "istio-system" "istio-ingressgateway") -}}
  {{- $igStatus := $ingressGateway.status | default dict }}
  {{- $igLoadBalancer := $igStatus.loadBalancer | default dict }}
  {{- $igIngress := $igLoadBalancer.ingress | default list }}
  {{- $igFirst := first $igIngress | default dict }}
  {{- if and (hasKey $igFirst "ip") .Values.bbtests.istio }}
  hostAliases:
  - ip: "{{ $igFirst.ip }}"
    hostnames:
    {{- range .Values.bbtests.istio.hosts }}
      - {{ tpl . $ }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  serviceAccountName: {{ .Chart.Name }}-script-sa
  containers:
    - name: {{ .Chart.Name }}-script-test
      securityContext:
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
      {{- if and .Values.bbtests .Values.bbtests.scripts .Values.bbtests.scripts.image }}
      image: {{ .Values.bbtests.scripts.image }}
      {{- else }}
      image: "registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.32.6"
      {{- end }}
      imagePullPolicy: IfNotPresent
      workingDir: /test
      command:
        - "/bin/bash"
        - "-c"
        - |
          trap 'curl -s -X POST http://localhost:15000/quitquitquit || true' ERR
          set -e
          if [[ -d /src && -n "$(ls /src/* 2>/dev/null)" ]]; then
            cp /src/* /test/
          fi
          {{- if .Values.bbtests }}
          {{- if .Values.bbtests.cypress }}
          {{- if .Values.bbtests.cypress.exports }}
          if [[ -d /exports && -n "$(ls /exports/* 2>/dev/null)" ]]; then
            mkdir exports
            cp /exports/* exports/
          fi
          {{- end }}
          {{- end }}
          {{- end }}
          if [[ -n "$(ls . 2>/dev/null)" ]]; then
            for script in *; do
              if [[ -d ${script} ]]; then
                continue;
              fi
              chmod +x ${script}
              echo "---"
              echo "Running ${script}..."
              echo "---"
              ./${script}
            done
          fi
          curl -s -X POST http://localhost:15000/quitquitquit || true
      volumeMounts:
        - name: script-tests
          mountPath: /src
        {{- if .Values.bbtests }}
        {{- if .Values.bbtests.cypress }}
        {{- if .Values.bbtests.cypress.exports }}
        - name: cypress-exports
          mountPath: /exports
        {{- end }}
        {{- end }}
        {{- end }}
        - name: workdir
          mountPath: /test
        {{- if .Values.bbtests }}
        {{- if .Values.bbtests.scripts }}
        {{- with .Values.bbtests.scripts.additionalVolumeMounts }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- if and .Values.bbtests .Values.bbtests.scripts }}
      {{- if or .Values.bbtests.scripts.envs .Values.bbtests.scripts.secretEnvs }}
      env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      {{- if .Values.bbtests.scripts.envs }}
      {{- range $k, $v := .Values.bbtests.scripts.envs }}
        - name: {{ tpl $k $ }}
          value: {{ tpl $v $ | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.bbtests.scripts.secretEnvs }}
      {{- tpl (toYaml .Values.bbtests.scripts.secretEnvs) $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if and .Values.bbtests .Values.bbtests.scripts }}
      resources:
      {{- if .Values.bbtests.scripts.resources }}
        requests:
          cpu: {{ .Values.bbtests.scripts.resources.requests.cpu | quote }}
          memory: {{ .Values.bbtests.scripts.resources.requests.memory | quote }}
        limits:
          cpu: {{ .Values.bbtests.scripts.resources.limits.cpu | quote }}
          memory: {{ .Values.bbtests.scripts.resources.limits.memory | quote }}
      {{- else }}
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
      {{- end }}
      {{- end }}
  restartPolicy: Never
  volumes:
    - name: script-tests
      configMap:
        name: "{{ .Chart.Name }}-script-config"
    {{- if .Values.bbtests }}
    {{- if .Values.bbtests.cypress }}
    {{- if .Values.bbtests.cypress.exports }}
    - name: cypress-exports
      configMap:
        name: "cypress-exports"
    {{- end }}
    {{- end }}
    {{- end }}
    - name: workdir
      emptyDir: {}
    {{- if .Values.bbtests }}
    {{- if .Values.bbtests.scripts }}
    {{- with .Values.bbtests.scripts.additionalVolumes }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- end }}
  imagePullSecrets:
    - name: private-registry
{{- end -}}
{{- end -}}

{{- define "gluon.tests.script-runner.base" }}
{{- if .Values.bbtests }}
{{- if .Values.bbtests.enabled }}

{{- if .Values.bbtests.scripts }}
{{- if .Values.bbtests.scripts.image }}
{{- include "gluon.tests.script-rbac" . }}
---
{{- end }}
{{- end }}

{{- include "gluon.tests.script-runner.tpl" . }}
{{- end }}
{{- end }}
{{- end }}

{{- define "gluon.tests.script-runner.overrides" -}}
{{- $values := (first .) }}
{{- if $values.Values.bbtests }}
{{- if and $values.Values.bbtests.scripts $values.Values.bbtests.enabled }}
{{- if $values.Values.bbtests.scripts.image }}
{{- include "gluon.tests.script-rbac" $values }}
---
{{- end }}
{{- include "gluon.util.merge" (append . "gluon.tests.script-runner.base") }}
{{- end }}
{{- end }}
{{- end }}
